### ISSUE TITLE
OpenSimulator Inventory Archives 

### ISSUE THREAD

**Issue by Dutchglory** [InWorldz/halcyon#459] opened 2018-07-08 07:51 UTC
if there's time please update  "OpenSimulator Inventory Archives" (IAR)  this is still not working...

thanks

**Comment by kf6kjg** [comment] 2018-08-05 18:26
Duplicate of: https://github.com/InWorldz/halcyon/issues/10

**Closed by kf6kjg** 2018-08-05 18:26 UTC
Labels: duplicate
