### ISSUE TITLE
Application Exception - DataStore DLL missing OpenSim.Data.MySQL.dll

### ISSUE THREAD

**Issue by frozengray** [InWorldz/halcyon#167] opened 2016-02-29 22:42 UTC
Visual Studio 2015, when trying to compile Halcyon in Debug, I get an error stating that OpenSim.Data.MySQL.dll is missing:

System.IO.FileNotFoundException was unhandled.
Message: An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll
Additional information: Could not load file or assembly 'file:///C:\opensim\bin\OpenSim.Data.MySQL.dll' or one of its dependencies. The system cannot find the file specified.

Please also see the attached logfiles. Did I miss a group of DLLs to download? Tried to copy over the MySQL dll from opensim and that just crashed the whole thing too :P Thank you for the help!

**Comment by frozengray** [comment] 2016-03-09 00:10
Ok built successfully, thank you! The DLLs are all there, I have started WHIP:
[IWVFS] Starting storage backend. is the last thing displayed on cmd.
Then start Halcyon, and the last thing on cmd is:
Assett Cache initialization OpenSim.Framework.Communication.Cache.AssetCache

Am I missing a configuration file? Both applications are waiting for the asset server to communicate with them. I have a MySQL service running with the Halcyon.ini configured for access. Thank you!!!

**Comment by ddaeschler** [comment] 2016-03-16 23:31
I had a report of this when someone build from source downloaded from the zipfile and windows restricted its ability to load.

If you downloaded the source via zip, try git clone instead

**Comment by frozengray** [comment] 2016-03-17 15:51
Great, git clone / build worked great. Now I'm missing a configuration step:
`2016-03-17 09:51:00,490 [ConsoleThread] INFO  OpenSim.Region.ClientStack.RegionApplicationBase - [REGION]: Starting HTTP server on 10.10.10.163:9000
2016-03-17 09:51:00,491 [ConsoleThread] INFO  OpenSim.Framework.Servers.HttpServer.BaseHttpServer - [BASE HTTP SERVER]: Starting HTTP server on port 9000
2016-03-17 09:51:00,493 [ConsoleThread] ERROR OpenSim.Framework.Servers.HttpServer.BaseHttpServer - [BASE HTTP SERVER]: Error - Access is denied
2016-03-17 09:51:00,493 [ConsoleThread] ERROR OpenSim.Framework.Servers.HttpServer.BaseHttpServer - [BASE HTTP SERVER]: Tip: Do you have permission to listen on port 9000?`

**Comment by mdickson** [comment] 2016-03-17 16:52
Check the source for BaseHttpServer.  There;s a comment that describes what you need to do. You need to set acls to enable access to the ports you have configured for the region server and other servers if you are running in grid mode.

            // netsh http add urlacl url=http://+:9000/ user=mdickson
            // netsh http add urlacl url=https://+:9016/ user=mdickson

User= should be your username.  The lines above open port 9000 for http and 9016 for https.

**Comment by ddaeschler** [comment] 2016-03-17 16:54
Mike,

Can you put in an enhancement request for printing that help out when someone hits he error? I'll probably grab it today

**Comment by mdickson** [comment] 2016-03-17 16:57
Yes will do, I'll just go ahead and add the code. Since I know the port it can reference it directly in the message

**Comment by frozengray** [comment] 2016-03-17 18:27
Ok, I don't know much about coding / variables but what worked for me was
(in an elevated cmd prompt):
netsh http add urlacl url=https://+:9001/ user=LocalUserName
Just building at work and going to work on a portable configuration bat
script or something, hopefully make single user deployment useful. Now I'm
getting another error:

2016-03-17 12:23:06,086 [ConsoleThread] INFO
OpenSim.Framework.PluginLoader`1 - [PLUGINS]: Plugin Loaded:
OpenSim.Data.MySQL
2016-03-17 12:23:09,243 [ConsoleThread] ERROR OpenSim.Application -
[APPLICATION]:
APPLICATION EXCEPTION DETECTED: System.UnhandledExceptionEventArgs

Exception: MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to
connect to any of the specified MySQL hosts. --->
System.Net.Sockets.SocketException (0x80004005): No such host is known


On Thu, Mar 17, 2016 at 10:57 AM, mdickson <notifications@github.com> wrote:

> Yes will do, I'll just go ahead and add the code. Since I know the port it
> can reference it directly in the message
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/InWorldz/halcyon/issues/167#issuecomment-197973038>
>



-- 
Tyler Dallison
479-715-1016
tylerdallison@gmail.com

**Comment by frozengray** [comment] 2016-03-17 18:27
Which is my MySQL config, I am running portable MySQL so I will check my settings and see again. What user / database configuration is appropriate? And I need to load tables? Thanks!

**Comment by frozengray** [comment] 2016-03-17 18:38
Got it, in the Halcyon.ini file the `storage_connection_string="Data Source=localhost;Database=inworldz;User ID=root;password=***missing***";`

**Comment by frozengray** [comment] 2016-03-17 18:40
Missing after Halcyon starts and asks for initial grid / master account info:
`Exception: System.IO.FileNotFoundException: Could not find file '...\halcyon\bin\Regions\default.xml'.
File name: '...\halcyon\bin\Regions\default.xml'`

**Comment by frozengray** [comment] 2016-03-17 18:46
For whatever reason default.xml.new needed to be renamed to default.xml but MySQL is still giving issues...
2016-03-17 12:43:49,136 [ConsoleThread] INFO  OpenSim.Region.OptionalModules.Avatar.FlexiGroups.NativeGroupDataProvider - [GROUPS]: MySQL connection exception: MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.Net.Sockets.SocketException (0x80004005): No such host is known
   at System.Net.Dns.GetAddrInfo(String name)

**Comment by jimtarber** [comment] 2016-03-17 22:46
Is this based with code from the current master?  There is a recent commit to do out-of-place updates to .xml files, to avoid creating 0-length files on disk space errors.  (Previously we would effectively lose the region XML files if a disk ran out of space.  The .xml.new file is an intermediate file used to store the new copy of the .xml file on changes, and should be very short-lived, unless the update of the .xml.new file fails, or the temporary rename of the old file to *.xml.old fails (e.g. if either was read-only).

Is this on a Linux machine? This may be related to the permissions of the files in question.  Perhaps the .new file is being created with limited file system permissions.

**Comment by frozengray** [comment] 2016-03-18 18:33
Yes, current master pulled via git clone on a Win 7 Pro x64 machine. Got the XML file configured properly. Do you have any suggestions for getting MySQL to work?

**Comment by ddaeschler** [comment] 2016-03-18 19:26
Halcyon can not connect to the database host you ahve configured. Please paste a sample of your Halcyon.ini file. Make sure to remove all sensitive information.

**Comment by frozengray** [comment] 2016-03-19 01:02
[Startup]
    ; Set this to true if you want to log crashes to disk
    ; this can be useful when submitting bug reports.
    save_crashes = false

    ; Directory to save crashes to if above is enabled
    ; (eg default is /opensimdir/crashes/*.txt or C:\opensim\crashes\*.txt)
    crash_dir = "crashes"

    ; Place to create a PID file
    ; PIDFile = "/tmp/my.pid"

    ; Http proxy support for llHTTPRequest and dynamic texture loading
    ; Set HttpProxy to the URL for your proxy server if you would like
    ; to proxy llHTTPRequests through a firewall
    ; HttpProxy = "http://proxy.com"
    ; Set HttpProxyExceptions to a list of regular expressions for
    ; URLs that you don't want going through the proxy such as servers
    ; inside your firewall, separate patterns with a ';'
    ; HttpProxyExceptions = ".mydomain.com;localhost"

    ; Set this to true if you are connecting your Halcyon regions to a grid
    ; Set this to false if you are running Halcyon in standalone mode
    gridmode = false

    startup_console_commands_file = "startup_commands.txt"
    shutdown_console_commands_file = "shutdown_commands.txt"

    ; To run a script every few minutes, set the script filename here
    ; timer_Script = "filename"

    ; ##
    ; ## REGIONS
    ; ##

    region_info_source = "filesystem"

    ; Draw objects on maptile.   This step might take a long time if you've
got a huge amount of
    ; objects, so you can turn it off here if you'd like.
    DrawPrimOnMapTile = true
    ; Use terrain texture for maptiles if true, use shaded green if false
    TextureOnMapTile = false

    ; Maximum total size, and maximum size where a prim can be physical
    NonPhysicalPrimMax = 256
    PhysicalPrimMax = 10
    ClampPrimSize = false

    ; ##
    ; ## STORAGE
    ; ##

    ; *** Prim Storage - only leave one storage_plugin uncommented ***
    ; --- Null stores nothing - effectively disabling persistence:
    ;storage_plugin = "OpenSim.Data.Null.dll"

    ; --- To use MySQL storage, supply your own connectionstring (this is
only an example):
    ;     note that the supplied account needs create privilegies if you
want it to auto-create needed tables.
     storage_plugin="OpenSim.Data.MySQL.dll"
     storage_connection_string="Data
Source=localhost;Database=inworldz;User ID=root;password=password";

    asset_database = "whip"

    ; Persistence of changed objects happens during regular sweeps. The
following control that behaviour to
    ; prevent frequently changing objects from heavily loading the region
data store.
    ; If both of these values are set to zero then persistence of all
changed objects will happen on every sweep.
    ;
    ; Objects will be considered for persistance in the next sweep when
they have not changed for this number of seconds
    MinimumTimeBeforePersistenceConsidered = 60
    ; Objects will always be considered for persistance in the next sweep
if the first change occurred this number of seconds ago
    MaximumTimeBeforePersistenceConsidered = 600

    ; ##
    ; ## PHYSICS
    ; ##

    ; if you would like to allow prims to be physical and move by physics
with the physical checkbox in the client set this to true.
    physical_prim = true

    ; Choose one of the physics engines below
    physics = InWorldz.PhysxPhysics

    ; ##
    ; ## PERMISSIONS
    ; ##

    permissionmodules = "DefaultPermissionsModule"

    ; If set to false, then, in theory, the server never carries out
permission checks (allowing anybody to copy
    ; any item, etc.  This may not yet be implemented uniformally.
    ; If set to true, then all permissions checks are carried out
    ; Default is false
    serverside_object_permissions = true

    allow_grid_gods = false

    use_aperture_server = yes
    aperture_server_port = 8000
    aperture_server_caps_token = 2960079

    core_connection_string = "Data Source=hostos;Database=inworldz;User
ID=root;Pooling=True;Min Pool Size=0;"
    rdb_connection_template = "Data Source={0};Database=inworldz;User
ID=root;Pooling=True;Min Pool Size=0;"

[SMTP]
    enabled=false

    ;enabled=true
    ;internal_object_host=lsl.opensim.local
    ;host_domain_header_from=10.10.10.163
    ;SMTP_SERVER_HOSTNAME=10.10.10.163
    ;SMTP_SERVER_PORT=25
    ;SMTP_SERVER_LOGIN=foo
    ;SMTP_SERVER_PASSWORD=bar


[Communications]
    ;InterregionComms = "LocalComms"
    InterregionComms = "RESTComms"

[Inventory]
    inventory_plugin = "InWorldz.Data.Inventory.Cassandra.dll"
    inventory_cluster = "local"
    legacy_inventory_source = "Data Source=hostos;Database=inworldz;User
ID=root;Pooling=True;Min Pool Size=5;"
    migration_active = true

[StandAlone]
    accounts_authenticate = false
    welcome_message = "Welcome to Halcyon"

    asset_source = "whip://password@localhost:32700"

    userDatabase_plugin = "OpenSim.Data.MySQL.dll"
    user_source = "Data Source=localhost;Database=inworldz;User
ID=root;password=password"

    ; Specifies the location and filename of the default inventory library
control file.  The path can be relative or absolute
    ; Default is ./inventory/Libraries.xml
    LibrariesXMLFile="./inventory/Libraries.xml"

    ; Specifies the location and filename of the inventory library assets
control file.  The path can be relative or absolute
    ; Setting is optional. Default is ./assets/AssetSets.xml
    AssetSetsXMLFile="./assets/AssetSets.xml"

    dump_assets_to_file = false

    ; Standalone-only http server URIs.
    map_server_uri = "http://10.10.10.163/map/"
    profile_server_uri = "http://10.10.10.163/profile/[AGENT_NAME]"


[Network]
    http_listener_port = 9000
    default_location_x = 1000
    default_location_y = 1000
    hostname = 10.10.10.163

    ; ssl config: Experimental!  The auto https config only really works
definately on windows XP now
    ; you need a Cert Request/Signed pair installed in the MY store with
the CN specified below
    ; you can use https on other platforms, but you'll need to configure
the httpapi yourself for now
    http_listener_ssl = false ; Also create a SSL server
    http_listener_cn = "localhost" ; Use the cert with the common name
    http_listener_sslport = 9001 ; Use this port for SSL connections
    http_listener_ssl_cert = "" ; Currently unused, but will be used for
OSHttpServer

    grid_server_url = "http://10.10.10.163:8001"
    grid_send_key = "null"
    grid_recv_key = "null"

    user_server_url = "http://10.10.10.163:8002"
    user_send_key = "null"
    user_recv_key = "null"

    asset_server_url = "whip://password@localhost:32700"

    ; The MessagingServer is a companion of the UserServer. It uses
    ; user_send_key and user_recv_key, too
    messaging_server_url = "http://10.10.10.163:8006"

    ; What is reported as the "X-Secondlife-Shard"
    ; Defaults to the user server url if not set
    ; The old default is "OpenSim", set here fro compatibility
    shard = "HalcyonHome"

    ; What is reported as the "User-Agent" when using llHTTPRequest
    ; Defaults to not sent if not set here. See the notes section in the
wiki at
    ; http://wiki.secondlife.com/wiki/LlHTTPRequest for comments on adding
    ; " (Mozilla Compatible)" to the text where there are problems with a
web server
    ;user_agent = "Halcyon LSL (Mozilla Compatible)"


[Chat]
    ; Controls whether the chat module is enabled.  Default is true.
    enabled = true;

    ; Distance in meters that whispers should travel.  Default is 10m
    whisper_distance = 10

    ; Distance in meters that ordinary chat should travel.  Default is 30m
    say_distance = 30

    ; Distance in meters that shouts should travel.  Default is 100m
    shout_distance = 100


[Messaging]
    ; Control which region module is used for instant messaging.
    ; Default is InstantMessageModule (this is the name of the core IM
module as well as the setting)
    InstantMessageModule = InstantMessageModule
    MessageTransferModule = MessageTransferModule
    OfflineMessageModule = OfflineMessageModule
    ; OfflineMessageURL = http://yourserver/Offline.php
    ; MuteListModule = MuteListModule
    ; MuteListURL = http://yourserver/Mute.php


; Uncomment the following to control the progression of daytime
; in the Sim.  The defaults are what is shown below
;[Sun]
    ; number of wall clock hours for an simulated day.  24.0 would mean
realtime
    ;day_length = 4
    ; Year length in days
    ;year_length = 60
    ; Day to Night Ratio
    ;day_night_offset = 0.45
    ; send a Sun update every update_interval # of frames.  A lower number
will
    ; make for smoother sun transition at the cost of network
    ;update_interval = 100


[Wind]
    ; Enables the wind module.  Default is true
    enabled = true

    ; How often should wind be updated, as a function of world frames.
Approximately 50 frames a second
    wind_update_rate = 30

    ; The Default Wind Plugin to load
    wind_plugin = ZephyrWind

    ; These settings are specific to the ConfigurableWind plugin
    ; To use ConfigurableWind as the default, simply change wind_plugin to
ConfigurableWind and uncomment the following.
    ; avg_strength  = 5.0
    ; avg_direction = 0.0
    ; var_strength  = 0.0
    ; var_direction = 0.0
    ; rate_change   = 1.0

    ; This setting is specific to the SimpleRandomWind plugin
    ; Adjusts wind strength. 0.0 = no wind, 1.0 = normal wind.  Default is
1.0
    strength = 1.0

[Cloud]
    ; Enable this to generate classic particle clouds above the sim.
    ; default is disabled - turn it on here
    enabled = false

    ; Density of cloud cover 0.0 to 1.0 Defult 0.5
    density = 0.5

    ; update interval for the cloud cover data returned by llCloud().
    ; default is 1000
    cloud_update_rate = 1000

[Trees]
    ; Enable this to allow the tree module to manage your sim trees,
including growing, reproducing and dying
    ; default is false
    active_trees = false

    ; Density of tree population
    tree_density = 1000.0


[GridInfo]
    ; These settings are used to return information on a get_grid_info call.
    ; Client launcher scripts and third-party clients make use of this to
    ; autoconfigure the client and to provide a nice user experience. If you
    ; want to facilitate that, you should configure the settings here
according
    ; to your grid or standalone setup.
    ;
    ; See http://opensimulator.org/wiki/GridInfo

    ;   uri: for grid this is the user server URI
    login = http://10.10.10.163:9000/

    ; long grid name: the long name of your grid
    gridname = "Standalone Halcyon Grid"

    ; short grid name: the short name of your grid
    gridnick = "halcyon"

    ; login page: optional: if it exists it will be used to tell the client
to use
    ;                       this as splash page
    ; currently unused
    ;welcome = http://10.10.10.163/welcome

    ; helper uri: optional: if it exists if will be used to tell the client
to use
    ;                       this for all economy related things
    ; currently unused
    ;economy = http://10.10.10.163:9000/

    ; web page of grid: optional: page providing further information about
your grid
    ; currently unused
    ;about = http://10.10.10.163/about/

    ; account creation: optional: page providing further information about
obtaining
    ;                             a user account on your grid
    ; currently unused
    ;register = http://10.10.10.163/register

    ; help: optional: page providing further assistance for users of your
grid
    ; currently unused
    ;help = http://10.10.10.163/help

    ; password help: optional: page providing password assistance for users
of your grid
    ; currently unused
    ;password = http://10.10.10.163/password


[Groups]
    Enabled = true

    ; This is the current groups stub in Region.CoreModules.Avatar.Groups
    ;Module  = Default

    ; The XmlRpcGroups implementation can be used against the publically
available service
    ; that I have made available for testing.  Your group data is not
guarenteed safe
    ; or available if you use this service, but it's available now and
seems to work.
    ; The PHP code for the service is available for you to deploy to your
own server.
    ;
    Module  = FlexiGroups
    Provider = Native
    NativeProviderDBType = MySQL
    NativeProviderConnString = "Data
Source=localhost;Database=inworldz;User
ID=root;password=password;Pooling=True;Min Pool Size=5;"

    ; This makes the XmlRpcGroups modules very chatty on the console.
    XmlRpcDebugEnabled     = false

[Profile]
    ProfileConnString = "DataSource=hostos;Database=inworldz;User
ID=root;Pooling=True;Min Pool Size=5;"

[Modules]
    ; Choose one
    AssetServices = "LocalAssetServicesConnector"
    UserServices = "LocalUserServicesConnector"

[InWorldz.PhysxPhysics]
    use_visual_debugger = true
    use_ccd = true

[Mesh]
    AllowMeshUpload = true

[SimulatorFeatures]
    MapImageServerURI="http://10.10.10.163:9000/"
    SearchServerURI="http://10.10.10.163:9000/"
    MeshEnabled=true
    PhysicsMaterialsEnabled=false

[ChatLogModule]
    Enabled = false
    Debug = false
    Backend = Cassandra12Backend
    SeedNode1 = 127.0.0.1

[GuestModule]
    Enabled = false
    GuestRegionName = "InWorldz Test"

[ChatFilterModule]
    Enabled = false

[AvatarRemoteCommands]
    Enabled = false


On Fri, Mar 18, 2016 at 1:26 PM, David Daeschler <notifications@github.com>
wrote:

> Halcyon can not connect to the database host you ahve configured. Please
> paste a sample of your Halcyon.ini file. Make sure to remove all sensitive
> information.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/InWorldz/halcyon/issues/167#issuecomment-198508957>
>



-- 
Tyler Dallison
479-715-1016
tylerdallison@gmail.com

**Comment by kf6kjg** [comment] 2018-04-05 18:33
@frozengray Was this ever resolved?

**Comment by kf6kjg** [comment] 2018-08-05 18:44
Never got an answer, so closing for now.  If the issue is still a problem for someone please reopen.

**Closed by kf6kjg** 2018-08-05 18:44 UTC
